function iirsos_coeffs_gen(coeff, gain)
    % Validate input matrices
    if isempty(coeff) || isempty(gain) || size(coeff, 2) ~= 6 || size(gain, 2) ~= 1
        error('Invalid input matrices. Please check the coefficient and gain matrices and try again.');
    end
    
    % Get the number of sections
    num_sections=length(gain)-1;

    % Prompt user for filename and open file for writing
    fname = input('enter filename for coefficients ','s');
    if isempty(fname)
        error('Filename is required. Please run the function again and enter a valid filename.');
    end
    fid = fopen(fname,'wt');
    if fid == -1
        error('Unable to open file for writing. Please check the file name and path, and try again.');
    end
    % Write header comments
    fprintf(fid,'// %s\n',fname);
    fprintf(fid,'// Generated by iirsos_coeffs_gen.m\n');
    
    % Define the number of sections
    fprintf(fid,'\n#define NUM_SECTIONS %d\n',num_sections);
    % Write the numerator coefficients 'b' in the C header file

    % i is the interator through sections
    fprintf(fid,'\nfloat b[NUM_SECTIONS][3] = { \n');
    for i=1:num_sections
      if i==num_sections
        fprintf(fid,'{%2.8E, %2.8E, %2.8E} };\n',...
        coeff(i,1)*gain(i),coeff(i,2)*gain(i),coeff(i,3)*gain(i));
      else
        fprintf(fid,'{%2.8E, %2.8E, %2.8E},\n',...
        coeff(i,1)*gain(i),coeff(i,2)*gain(i),coeff(i,3)*gain(i));
      end
    end

    % Write the numerator coefficients 'a' in the C header file
    % i is the interator through sections
    fprintf(fid,'\nfloat a[NUM_SECTIONS][3] = { \n');
    for i=1:num_sections
      if i==num_sections
        fprintf(fid,'{%2.8E, %2.8E, %2.8E} };\n',...
        coeff(i,4),coeff(i,5),coeff(i,6));
      else
        fprintf(fid,'{%2.8E, %2.8E, %2.8E},\n',...
        coeff(i,4),coeff(i,5),coeff(i,6));
      end
    end

fclose(fid);
